import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased max-w-4xl m-auto my-4`}
      >
        <header className="w-full flex justify-between p-4">
          <Link
            href={"/add-note"}
            className="bg-indigo-600 p-2 rounded-md hover:bg-indigo-500 duration-100"
          >
            add new note
          </Link>

          <h1 className="text-xl font-extrabold">
            <Link href={"/"}>Notes</Link>
          </h1>
        </header>
        {children}
      </body>
    </html>
  );
}
